name: Update Posts
on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:         # Allows manual triggers

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to push changes
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for proper git history

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests python-dotenv

      - name: Fetch posts from Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: |
          python fetch_posts.py
          # Store the last processed ID
          if [ -f last_id.txt ]; then
            echo "Resuming from last ID"
          else
            echo "0" > last_id.txt
            echo "Starting full history fetch"
          fi

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatic token
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add posts.json
          git diff --quiet && git diff --staged --quiet || (
            git commit -m "Update posts [auto]"
            git push https://x-access-token:$GH_TOKEN@github.com/${{ github.repository }}.git
          )
