name: Update Posts
on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every hour at minute 0
  workflow_dispatch:     # Allows manual runs

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: pip install requests python-dotenv
      
      - name: Fetch posts
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: python fetch_posts.py
      
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add posts.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update posts" && git push)
